name: Update Prod composer.json
on:
  push:
    branches: [main]
    paths:
      - 'composer.json'
      - 'composer.lock'
jobs:
  create_composer_json:
    name: Create Production composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: 'production'
      - name: Update File
        run: |
          curl https://github.com/CuBoulder/nextpress-project-template/blob/main/composer.json > composer.json
          curl https://github.com/CuBoulder/nextpress-project-template/blob/main/composer.lock > composer.lock
      - name: Push to production branch
        run: |
          git config --local user.name "${{ github.actor }}"
          git add composer.*
          git commit -m "automated update"
          git push